package com.example.stocksentry.dto;

import lombok.Data;

@Data
public class User {
    private String userId; // Unique ID generated by backend
    private String name;   // User-provided name
    private String email;  // User email for notifications
    private String phoneNumber; // User phone number for SMS notifications
}
